# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install and build
        run: |
          npm install
          npm run build

# 使用不同的actions工具进行文件上传到开发服务器
# 直接将dist目录中所有文件上传到actions-vue目录中
#      - name: SSH Server Deploy
#        uses: kostya-ten/ssh-server-deploy@v4
#        with:
#          host: ${{ secrets.HOST }}
#          port: ${{ secrets.PORT }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          scp_source: ./dist/*
#          scp_target: /usr/local/app/actions-vue/

      - name: deploy package
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: ./dist/*
          target: /usr/local/app/actions-vue/,
          strip_components: 1


#      - name: deploy package
#        uses: cross-the-world/scp-pipeline@master
#        with:
#          host: ${{ secrets.HOST }}
#          port: ${{ secrets.PORT }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          local: ./dist/*
#          remote: /usr/local/app/actions-vue/
