# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install, build, and test
        run: |
          npm install
          npm run build:test --if-present

      - name: deploy package
        uses: mdallasanta/ssh-scp-deploy@v1.1.0
        with:
          local: './dist/'                                             # Local file path - REQUIRED false - DEFAULT ./
          remote: '/usr/local/app/actions-vue/'                        # Remote file path - REQUIRED false - DEFAULT ~/
          host: ${{secrets.HOST}}                                      # Remote server address - REQUIRED true
          port: ${{secrets.PORT}}                                      # Remote server port - REQUIRED false - DEFAULT 22
          user: ${{secrets.USERNAME}}                                      # Remote server user - REQUIRED true
          password: ${{secrets.PASSWORD}}                              # User password - REQUIRED at least one of "password" or "key"
          pre_upload: echo "This will be executed before the upload!"  # Command to run via ssh before scp upload - REQUIRED false
          post_upload: echo "This will be executed after the upload!"  # Command to run via ssh after scp upload - REQUIRED false
          ssh_options: -o StrictHostKeyChecking=no                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
          scp_options: -v
