# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build:test --if-present
          tar -zcvf release.tgz dist

      - name: deploy package
        uses: garygrossgarten/github-action-scp@release
        with:
          local: release.tgz
          remote: /usr/local/app/actions-vue/release.tgz
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /usr/local/app/actions-vue
            tar -zxvf release.tgz
